package com.example.demo.mock;

import com.example.demo.common.domain.ResourceNotFoundException;
import com.example.demo.user.domain.User;
import com.example.demo.user.domain.UserStatus;
import com.example.demo.user.service.port.UserRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeUserRepository implements UserRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong();
    private final List<User> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Optional<User> findByIdAndStatus(long id, UserStatus userStatus) {
        return data.stream().filter(item -> Objects.equals(item.getId(), id) && Objects.equals(item.getStatus(), userStatus)).findFirst();
    }

    @Override
    public Optional<User> findByEmailAndStatus(String email, UserStatus userStatus) {
        return data.stream().filter(item -> Objects.equals(item.getEmail(), email) && Objects.equals(item.getStatus(), userStatus)).findFirst();
    }

    @Override
    public User save(User user) {
        if (user.getId() == null || user.getId() == 0) {
            User newUser = User.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .email(user.getEmail())
                    .lastLoginAt(user.getLastLoginAt())
                    .status(user.getStatus())
                    .certificationCode(user.getCertificationCode())
                    .address(user.getAddress())
                    .nickname(user.getNickname())
                    .build();
            data.add(newUser);
            return newUser;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), user.getId()));
            data.add(user);
            return user;
        }
    }

    @Override
    public Optional<User> findById(long id) {
        return data.stream().filter(item -> Objects.equals(item.getId(), id)).findFirst();
    }

    @Override
    public User getById(long id) {
        return data.stream().filter(item -> Objects.equals(item.getId(), id)).findFirst()
                .orElseThrow(() -> new ResourceNotFoundException("Users", id));
    }
}
